steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-west2-docker.pkg.dev/${PROJECT_ID}/mywebapp-docker-repo/triggered-app-image', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-west2-docker.pkg.dev/${PROJECT_ID}/mywebapp-docker-repo/triggered-app-image']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'mywebappservice', '--image', 'us-west2-docker.pkg.dev/${PROJECT_ID}/mywebapp-docker-repo/triggered-app-image','--region', 'us-west2', '--allow-unauthenticated', '--port', '8501']